//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USUARIOS
    {
        public int Identificacion { get; set; }
        public string Nombre_Completo { get; set; }
        public string Fecha_Nacimiento { get; set; }
        public string Contraseña { get; set; }
        public byte[] Foto { get; set; }
        public string Correo { get; set; }
        public int Telefono { get; set; }
    }
}
